name: Code Validation

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ensure this matches the Node version used in development

      - name: Install dependencies
        run: npm ci

      - name: Validate TypeScript
        run: npx tsc --noEmit

      - name: Lint with ESLint
        run: npx eslint --fix . --ext .ts,.tsx

      - name: Check formatting with Prettier
        run: npx prettier --write . --ignore-unknown
